<!DOCTYPE html>
<!-- Template -->
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>QR Text Generator</title>
</head>

<body> <!-- BODY START -->

	<?php
	error_reporting(E_ALL); 

	// Test: http://localhost/wrk/crunserver/appdev/php_qr
	// Test: http://localhost/ltx/sw/php_qr
	// Test: https://joembedded.de/...

	$plaintxt = urldecode(@$_REQUEST['plaintxt'] ?? "Hello World");

	?>
	<h1>QR Text Generator</h1>
	General generator for QR codes, based on
	<a href="http://sourceforge.net/apps/mediawiki/phpqrcode" target="_blank">http://sourceforge.net/apps/mediawiki/phpqrcode</a><br>
	This is just a placeholder. The QR codes themselves are generated by './ltx_qr.php?...'<br>
	QR codes can be larger than 2k. Line breaks are encoded if present in the input field.
	<hr>

	Examples (more: <a href="https://en.wikipedia.org/wiki/Uniform_Resource_Identifier" target="_blank">URI</a>):
	<ul>
		<li>'TXT-ln:' - 'Say' for BlxDahboard, ln: EN DE IT ... - Example 'TXT-DE:Willkommen'</li>
		<li>'CMD:cmd' - Command 'cmd' for BlxDasboard. - Example 'CMD: .crun crun/scan433sdi.crun'</li>
		<li>'MAC:mac OT:ot' - MAC/Ownertoken for BlxDasboard - Example 'MAC:0011223344556677 OT:0122345789ABCDEF'</li>
		<li>'MAC:mac PIN:ot' - MAC/PIN for BlxDasboard - Example 'MAC:0011223344556677 PIN:123456'</li>
		<li>'http(s)://link' - Simple link</li>
		<li>'WIFI:S:ssid;T:wpa;P:password;' - Wifi, ssid:Name of Network, wpa:Encr., use WPA, p:Password - Example 'WIFI:S:MyHome;T:WPA;P:SecRet;'</li>
		<li>'geo:lat,lng - GeoLocation (with optional Search-data) - Example 'geo:49.010,8.404?q=Karlsruhe'</li>
	</ul>
	<br>

	<form action="./">
		<label for="plaintxt">Enter Plain-Text (Link, Kommando, ...):</label><br>
		<textarea rows="3" cols="120" id="plaintxt" name="plaintxt"><?php echo ($plaintxt); ?></textarea>
		<br>
		<br>
		<input type="submit" value="Submit">
	</form>
	<br>
	-----QR below contains exactly:-----
	<pre><?php echo $plaintxt; ?></pre>-------------------------------------------<br>
	<img src="./ltx_qr.php?text=<?php echo (urlencode($plaintxt)); ?>">


</body> <!-- BODY END -->

</html>